In [13]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [14]:
##Input and libraries
gdprkaggle="C:/Users/Alex/Desktop/py/input/gdpr_fines.csv"
allfinesgit="C:/Users/Alex/Desktop/py/input/all_fines.csv"
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import matplotlib.cm as cm

In [15]:
##Read data from csv
data1=pd.read_csv(gdprkaggle)
data2=pd.read_csv(allfinesgit)

In [17]:
### here starts Preprocessing

##Display data information to get an overview
data1.info()
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               121 non-null    object
 1   Authority             121 non-null    object
 2   Date                  121 non-null    object
 3   Fine [€]              121 non-null    object
 4   Controller/Processor  121 non-null    object
 5   Quoted Art.           121 non-null    object
 6   Type                  121 non-null    object
 7   Infos                 121 non-null    object
dtypes: object(8)
memory usage: 3.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               250 non-null    int64
 1   picture          250 non-null    object
 2   country          250 non-null    object
 3   price            250 non-null    int64
 4   authority        250 non-null    object
 5   date             250 non-null    object
 6   org_fined        250 non-null    object
 7   articleViolated  250 non-null    object
 8   type             250 non-null    object
 9   source           250 non-null    object
 10  summary          250 non-null    object
dtypes: int64(2), object(9)
memory usage: 12.8+ KB

In [18]:
##capitalize/upper names of dataset2 
##kaggle allready preprocesses data1 a bit so we will focuse more on dataset2
data2.columns = map(lambda x: str(x).capitalize(), data2.columns)

In [19]:
data2.columns

Index(['Id', 'Picture', 'Country', 'Price', 'Authority', 'Date', 'Org_fined',
       'Articleviolated', 'Type', 'Source', 'Summary'],
      dtype='object')

In [20]:
data1.columns

Index(['Country', 'Authority', 'Date', 'Fine [€]', 'Controller/Processor',
       'Quoted Art.', 'Type', 'Infos'],
      dtype='object')

In [21]:
##Rename same columns
data2.columns = ['Id', 'Picture', 'Country', 'Fine', 'Authority', 'Date', 'Org_fined','ArticleViolated', 'Type', 'Source', 'Summary']
data1.columns = ['Country', 'Authority', 'Date', 'Fine', 'Org_fined','ArticleViolated', 'Type', 'Infos']
##Check for NA
print(data1.isna().sum())
print(data2.isna().sum())

Country            0
Authority          0
Date               0
Fine               0
Org_fined          0
ArticleViolated    0
Type               0
Infos              0
dtype: int64
Id                 0
Picture            0
Country            0
Fine               0
Authority          0
Date               0
Org_fined          0
ArticleViolated    0
Type               0
Source             0
Summary            0
dtype: int64

In [22]:
data1.head(2)

,Country,Authority,Date,Fine,Org_fined,ArticleViolated,Type,Infos
0,ROMANIA,Romanian National Supervisory Authority for Pe...,2019-11-25,"11,000",Courier Services Company,Art. 32 GDPR,Insufficient technical and organisational meas...,link
1,ROMANIA,Romanian National Supervisory Authority for Pe...,2019-11-22,"2,000",BNP Paribas Personal Finance S.A.,"Art. 12 GDPR, Art. 17 GDPR",Insufficient fulfilment of data subjects rights,link

In [23]:
data2.head(2)

,Id,Picture,Country,Fine,Authority,Date,Org_fined,ArticleViolated,Type,Source,Summary
0,1,https://www.privacyaffairs.com/wp-content/uplo...,Poland,9380,Polish National Personal Data Protection Offic...,2019-10-18,Polish Mayor,Art. 28 GDPR,Non-compliance with lawful basis for data proc...,https://uodo.gov.pl/decyzje/ZSPU.421.3.2019,<p>No data processing agreement has been concl...
1,2,https://www.privacyaffairs.com/wp-content/uplo...,Romania,2500,Romanian National Supervisory Authority for Pe...,2019-10-17,UTTIS INDUSTRIES,"Art. 12 GDPR, Art. 13 GDPR, Art. 5 (1) c) GDPR...",Information obligation non-compliance,https://www.dataprotection.ro/?page=A_patra_am...,<p>A controller was sanctioned because he had ...

In [24]:
## Join both dataframes (inner join for clustering preparation)
dataset_clust = pd.concat([data1, data2], axis=0, sort=True, join="inner")
dataset_clust.info()
print(dataset_clust.isna().sum())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 371 entries, 0 to 249
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ArticleViolated  371 non-null    object
 1   Authority        371 non-null    object
 2   Country          371 non-null    object
 3   Date             371 non-null    object
 4   Fine             371 non-null    object
 5   Org_fined        371 non-null    object
 6   Type             371 non-null    object
dtypes: object(7)
memory usage: 13.0+ KB
ArticleViolated    0
Authority          0
Country            0
Date               0
Fine               0
Org_fined          0
Type               0
dtype: int64

In [25]:
## Join both dataframes (outer join for overall view and plotting)
dataset = pd.concat([data1, data2], axis=0, sort=True, join="outer")
dataset.info()
print(dataset.isna().sum())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 371 entries, 0 to 249
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ArticleViolated  371 non-null    object
 1   Authority        371 non-null    object
 2   Country          371 non-null    object
 3   Date             371 non-null    object
 4   Fine             371 non-null    object
 5   Id               250 non-null    float64
 6   Infos            121 non-null    object
 7   Org_fined        371 non-null    object
 8   Picture          250 non-null    object
 9   Source           250 non-null    object
 10  Summary          250 non-null    object
 11  Type             371 non-null    object
dtypes: float64(1), object(11)
memory usage: 21.7+ KB
ArticleViolated      0
Authority            0
Country              0
Date                 0
Fine                 0
Id                 121
Infos              250
Org_fined            0
Picture            121
Source             121
Summary            121
Type                 0
dtype: int64

In [26]:
dataset.head(2)

,ArticleViolated,Authority,Country,Date,Fine,Id,Infos,Org_fined,Picture,Source,Summary,Type
0,Art. 32 GDPR,Romanian National Supervisory Authority for Pe...,ROMANIA,2019-11-25,"11,000",NaN,link,Courier Services Company,NaN,NaN,NaN,Insufficient technical and organisational meas...
1,"Art. 12 GDPR, Art. 17 GDPR",Romanian National Supervisory Authority for Pe...,ROMANIA,2019-11-22,"2,000",NaN,link,BNP Paribas Personal Finance S.A.,NaN,NaN,NaN,Insufficient fulfilment of data subjects rights

In [27]:
##look for unnecessary columns
dataset.columns

Index(['ArticleViolated', 'Authority', 'Country', 'Date', 'Fine', 'Id',
       'Infos', 'Org_fined', 'Picture', 'Source', 'Summary', 'Type'],
      dtype='object')

In [28]:
# delete "," and "." from Fine values, Country values to uppercase
dataset['Country'] = dataset['Country'].str.upper()
dataset["Fine"] = dataset["Fine"].astype(str)
dataset["Fine"] = dataset["Fine"].str.replace(r'.', '')
dataset["Fine"] = dataset["Fine"].str.replace(r',', '')

In [29]:
##check if fines are all numbers
for i in dataset["Fine"]:
    if(i.isdigit()):
        continue
    else:
        print(i)

Unknown
Unknown
Unknown
Unknown
Unknown
Unknown

In [30]:
# Resetting the index of dataframe
dataset = dataset.reset_index()
# Delete following columns
dataset_clean = dataset.drop(columns=['Id','Infos','Picture', 'Source', 'Summary', 'index'])
dataset

,index,ArticleViolated,Authority,Country,Date,Fine,Id,Infos,Org_fined,Picture,Source,Summary,Type
0,0,Art. 32 GDPR,Romanian National Supervisory Authority for Pe...,ROMANIA,2019-11-25,11000,NaN,link,Courier Services Company,NaN,NaN,NaN,Insufficient technical and organisational meas...
1,1,"Art. 12 GDPR, Art. 17 GDPR",Romanian National Supervisory Authority for Pe...,ROMANIA,2019-11-22,2000,NaN,link,BNP Paribas Personal Finance S.A.,NaN,NaN,NaN,Insufficient fulfilment of data subjects rights
2,2,Art. 6 GDPR,Spanish Data Protection Authority (aepd),SPAIN,2019-11-21,60000,NaN,link,Viaqua Xestión Integral Augas de Galicia,NaN,NaN,NaN,Insufficient legal basis for data processing
3,3,"Art. 5 GDPR, Art. 6 GDPR, Art. 13 GDPR, Art. 1...",French Data Protection Authority (CNIL),FRANCE,2019-11-21,500000,NaN,link,Futura Internationale,NaN,NaN,NaN,Insufficient fulfilment of data subjects rights
4,4,Art. 32 GDPR,Spanish Data Protection Authority (aepd),SPAIN,2019-11-19,60000,NaN,link,Corporación radiotelevisión espanola,NaN,NaN,NaN,Insufficient technical and organisational meas...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
366,245,"Art. 33 GDPR, Art. 34 GDPR",Data Protection Authority of Hamburg,GERMANY,2019-01-01,20000,246.0,NaN,https://datenschutz-hamburg.de/assets/pdf/28._...,https://www.privacyaffairs.com/wp-content/uplo...,https://datenschutz-hamburg.de/assets/pdf/28._...,<p>HVV GmbH had not reported a data breach to ...,Failure to implement sufficient measures to en...
367,246,"Art. 5 GDPR, Art. 32 GDPR",Data Protection Authority of Baden-Wuerttemberg,GERMANY,2019-04-04,80000,247.0,NaN,Company in the financial sector,https://www.privacyaffairs.com/wp-content/uplo...,https://www.baden-wuerttemberg.datenschutz.de/...,"<p>The fine was issued because, in April 2019,...",Failure to implement sufficient measures to en...
368,247,"Art. 5 GDPR, Art. 6 GDPR",Data Protection Authority of Nordrhein-Westfalen,GERMANY,2019-08-05,200,248.0,NaN,Private person (YouTube-Channel),https://www.privacyaffairs.com/wp-content/uplo...,https://www.youtube.com/watch?v=wFBrgJIkDwI,<p>The private person has an insufficient lega...,Failure to comply with data processing principles
369,248,"Art. 5 GDPR, Art. 32 GDPR",Data Protection Authority of Baden-Wuerttemberg,GERMANY,2019-10-24,100000,249.0,NaN,Food company,https://www.privacyaffairs.com/wp-content/uplo...,https://www.baden-wuerttemberg.datenschutz.de/...,<p>Upon creation of an applicant portal where ...,Failure to implement sufficient measures to en...
370,249,"Art. 5 GDPR, Art. 6 GDPR, Art. 32 GDPR",Hellenic Data Protection Authority (HDPA),GREECE,2019-12-19,150000,250.0,NaN,Aegean Marine Petroleum Network Inc.,https://www.privacyaffairs.com/wp-content/uplo...,http://www.dpa.gr/APDPXPortlets/htdocs/documen...,<p>The Aegean Marine Petroleum Network Inc. fa...,Failure to comply with data processing principles

In [31]:
# Map uniqe Country_code for Country's in dataset
dataset_clean['Country_code'] = dataset_clean['Country'].map({'AUSTRIA': '01',
                                                              'BELGIUM': '02',
                                                              'BULGARIA': '03',
                                                              'CROATIA': '04',
                                                              'CYPRUS': '05',
                                                              'CZECH REPUBLIC': '06',
                                                              'DENMARK': '07',
                                                              'FRANCE': '08',
                                                              'GERMANY': '09',
                                                              'GREECE': '10',
                                                              'HUNGARY': '11',
                                                              'ICELAND': '12',
                                                              'ITALY': '13',
                                                              'LATVIA': '14',
                                                              'LITHUANIA': '15',
                                                              'MALTA': '16',
                                                              'THE NETHERLANDS': '17',
                                                              'NETHERLANDS' : '17',
                                                              'NORWAY': '18',
                                                              'POLAND': '19',
                                                              'PORTUGAL': '20',
                                                              'ROMANIA': '21',
                                                              'SLOVAKIA': '22',
                                                              'SPAIN': '23',
                                                              'SWEDEN': '24',
                                                              'UNITED KINGDOM': '25'})
dataset_clean.head(2)

,ArticleViolated,Authority,Country,Date,Fine,Org_fined,Type,Country_code
0,Art. 32 GDPR,Romanian National Supervisory Authority for Pe...,ROMANIA,2019-11-25,11000,Courier Services Company,Insufficient technical and organisational meas...,21
1,"Art. 12 GDPR, Art. 17 GDPR",Romanian National Supervisory Authority for Pe...,ROMANIA,2019-11-22,2000,BNP Paribas Personal Finance S.A.,Insufficient fulfilment of data subjects rights,21

In [33]:
##Check for mistakes
Trueness = pd.isna(clean["Country_code"])
linecount=0
for line in Trueness:
    linecount+=1
    if(line == True):
        print(clean["Country"][linecount-1])

NameError: name 'clean' is not defined

In [38]:
#Save data
dataset_clean.to_csv("C:/Users/Alex/Desktop/py/output/df_clean.csv")

In [40]:
# Read new CSV
clean=pd.read_csv("C:/Users/Alex/Desktop/py/input/clean.csv")

In [41]:
# Delete the column "Column" from clean dataframe
clean = clean.drop(columns=['Column'])

In [42]:
# Generate column with number of Fines_applied
clean['Fines_applied'] = clean['ArticleViolated'].str.count(',') + 1
clean.head(2)

,ArticleViolated,Authority,Country,Date,Fine,Org_fined,Type,Country_code,Fines_applied
0,Art. 32 GDPR,Romanian National Supervisory Authority for Pe...,ROMANIA,2019-11-25,11000,Courier Services Company,Insufficient technical and organisational meas...,21,1
1,"Art. 12 GDPR, Art. 17 GDPR",Romanian National Supervisory Authority for Pe...,ROMANIA,2019-11-22,2000,BNP Paribas Personal Finance S.A.,Insufficient fulfilment of data subjects rights,21,2

In [43]:
# Read CSV with GDP per capita
gdp=pd.read_csv("C:/Users/Alex/Desktop/py/input/gdp_einwohner.csv")
gdp.head(2)

   Country  GDP_2019
0  AUSTRIA     38250
1  BELGIUM     35900

In [44]:
clean["Country_code"].isna().sum()

0

In [45]:
# Map GDP per Capita
clean['GDP_pc_2019'] = clean['Country'].map({'AUSTRIA':'38250',
                                          'BELGIUM':'35900',
                                          'BULGARIA':'6800',
                                          'CYPRUS':'24250',
                                          'CZECH REPUBLIC':'18000',
                                          'GERMANY':'35980',
                                          'GREECE':'18150',
                                          'DENMARK':'49190',
                                          'SPAIN':'25170',
                                          'FRANCE':'33270',
                                          'CROATIA':'12480',
                                          'HUNGARY':'13180',
                                          'ICELAND':'38840',
                                          'ITALY':'26860',
                                          'LITHUANIA':'13880',
                                          'LATVIA':'12490',
                                          'MALTA':'22040',
                                          'THE NETHERLANDS':'42020',
                                          'NETHERLANDS':'42020',
                                          'NORWAY':'69890',
                                          'POLAND':'12980',
                                          'PORTUGAL':'18550',
                                          'ROMANIA':'9130',
                                          'SWEDEN':'43840',
                                          'SLOVAKIA':'15890',
                                          'UNITED KINGDOM':'32960'
                                         })

In [46]:
# Export clean dataframe to CSV
clean.to_csv('C:/Users/Alex/Desktop/py/output/gpdr_aftercleaning.csv')

In [47]:
# Read data from CSV
newgdp = pd.read_csv("C:/Users/Alex/Desktop/py/input/gdp_land.csv")
# Renme columns
newgdp.columns = ['Country', 'GDP_2019']
# Bringing all countries to uppercase and deleting "," from GDP_2019 column values
newgdp["Country"] = newgdp["Country"].str.upper()
newgdp["GDP_2019"] = newgdp["GDP_2019"].str.replace(r',', '')
newgdp.head(2)

          Country   GDP_2019
0         GERMANY   3947620
1  UNITED KINGDOM   2855297

In [48]:
# Map GDP per Country
clean['GDP_2019'] = clean['Country'].map({'GERMANY':'3947620'
                                          ,'UNITED KINGDOM':'2855297'
                                          ,'FRANCE':'2777535'
                                          ,'ITALY':'2083864'
                                          ,'SPAIN':'1419042'
                                          ,'THE NETHERLANDS':'913658'
                                          ,'NETHERLANDS':'913658'
                                          ,'POLAND':'585664'
                                          ,'SWEDEN':'556086'
                                          ,'BELGIUM':'542761'
                                          ,'AUSTRIA':'455286'
                                          ,'NORWAY':'434167'
                                          ,'DENMARK':'355675'
                                          ,'CZECH REPUBLIC':'245226'
                                          ,'PORTUGAL':'240675'
                                          ,'ROMANIA':'239553'
                                          ,'GREECE':'218032'
                                          ,'HUNGARY':'157883'
                                          ,'SLOVAKIA':'105905'
                                          ,'BULGARIA':'65133'
                                          ,'CROATIA':'60972'
                                          ,'LITHUANIA':'53429'
                                          ,'LATVIA':'34409'
                                          ,'ICELAND':'25878'
                                          ,'CYPRUS':'24962'
                                          ,'MALTA':'14553'
                                         })

In [49]:
##Check for mistakes
Trueness = pd.isna(clean["GDP_2019"])
linecount=0
for line in Trueness:
    linecount+=1
    if(line == True):
        print(clean["GDP_2019"][linecount-1])

In [50]:
clean["GDP_2019"] = clean["GDP_2019"].astype(int)
clean["GDP_2019"] = clean["GDP_2019"] * 1.12
clean["GDP_2019"] = clean["GDP_2019"].astype(int)

In [51]:
clean

,ArticleViolated,Authority,Country,Date,Fine,Org_fined,Type,Country_code,Fines_applied,GDP_pc_2019,GDP_2019
0,Art. 32 GDPR,Romanian National Supervisory Authority for Pe...,ROMANIA,2019-11-25,11000,Courier Services Company,Insufficient technical and organisational meas...,21,1,9130,268299
1,"Art. 12 GDPR, Art. 17 GDPR",Romanian National Supervisory Authority for Pe...,ROMANIA,2019-11-22,2000,BNP Paribas Personal Finance S.A.,Insufficient fulfilment of data subjects rights,21,2,9130,268299
2,Art. 6 GDPR,Spanish Data Protection Authority (aepd),SPAIN,2019-11-21,60000,Viaqua XestiÄ‚Ĺ‚n Integral Augas de Galicia,Insufficient legal basis for data processing,23,1,25170,1589327
3,"Art. 5 GDPR, Art. 6 GDPR, Art. 13 GDPR, Art. 1...",French Data Protection Authority (CNIL),FRANCE,2019-11-21,500000,Futura Internationale,Insufficient fulfilment of data subjects rights,8,5,33270,3110839
4,Art. 32 GDPR,Spanish Data Protection Authority (aepd),SPAIN,2019-11-19,60000,CorporaciÄ‚Ĺ‚n radiotelevisiÄ‚Ĺ‚n espanola,Insufficient technical and organisational meas...,23,1,25170,1589327
...,...,...,...,...,...,...,...,...,...,...,...
354,"Art. 33 GDPR, Art. 34 GDPR",Data Protection Authority of Hamburg,GERMANY,2019-01-01,20000,https://datenschutz-hamburg.de/assets/pdf/28._...,Failure to implement sufficient measures to en...,9,2,35980,4421334
355,"Art. 5 GDPR, Art. 32 GDPR",Data Protection Authority of Baden-Wuerttemberg,GERMANY,2019-04-04,80000,Company in the financial sector,Failure to implement sufficient measures to en...,9,2,35980,4421334
356,"Art. 5 GDPR, Art. 6 GDPR",Data Protection Authority of Nordrhein-Westfalen,GERMANY,2019-08-05,200,Private person (YouTube-Channel),Failure to comply with data processing principles,9,2,35980,4421334
357,"Art. 5 GDPR, Art. 32 GDPR",Data Protection Authority of Baden-Wuerttemberg,GERMANY,2019-10-24,100000,Food company,Failure to implement sufficient measures to en...,9,2,35980,4421334
358,"Art. 5 GDPR, Art. 6 GDPR, Art. 32 GDPR",Hellenic Data Protection Authority (HDPA),GREECE,2019-12-19,150000,Aegean Marine Petroleum Network Inc.,Failure to comply with data processing principles,10,3,18150,244195

In [53]:
# Save final clean data after processing und Python + OpenRefine
clean.to_csv('C:/Users/Alex/Desktop/py/output/data_gdpr_afterclean.csv')